use_frameworks!

target 'SmalltalkCollections_Example' do
  pod 'SmalltalkCollections', :path => '../'

  target 'SmalltalkCollections_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
